### ISSUE TITLE
Scan not working

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#1]
Hi, i will post bugs here than on the forum, i think it's better to manage here for you, and cleaner. You can remove an issue when it's done.

Scan  in Option menu is not working, it do nothing when i click it.
I think/wish that's the function i ask you to show on a system the files present on the directory and not write in the gamelist.xml.

It is really an important option to began manage games with your Webtropie :D 
UniversalScreenScrapper forgot so many games without informations, and not write them on XML.
I think it can be better to show these files with a different color.
Thnaks

**Comment by gazpan** [comment]
Hi, I've pushed an update to this, it should show new files prefixed with the word "New: " in the title, the colour is the same as a normal game colour, directories are the secondary colour. It will show empty directories only if set in the settings file. (There's also a WanEditMode option).

**Comment by gazpan** [comment]
... I think still to do is that it would be nice to be able to filter these new files easily as you suggested

**Comment by Darknior** [comment]
Excellent it works very well and fast :)
I love this feature, but if you can use an other color it can help to found them to work on.
One third color for games not in gamelist.xml

The filter can help too :)

**Comment by gazpan** [comment]
Hi, new games should show in a new colour now, you can also type "New:" to filter those new games.
... do you think that the rom modified file date / time would be a useful optional field to add to the list of selectable fields? or are these changes sufficient.

**Comment by Darknior** [comment]
It is really excellent :)
With the new color it is already fantastic to help on work, thanks a lot :)

BUT i have a bug. When i scan my directories, it works for the 4 first games and after it detect all the games, in the gamelist.xml or not :(
```
5) ASSAULT FORCE 3D (USA).ATR
NEW) ASSAULT FORCE 3D (USA).ATR
```
It is a BIG bug :p 
I have a little list like my **SUPER GRAFX** where all the games are detected as **NEW** :(
On an other little list like my **PORTS** list i don't have this bug ... i can't explain why ?

There is also a bug with the ".", you don't use the last one to crop the string.
`NEW) MS. PAC-MAN (USA).ZIP`
It works when you read it from the gamelist but you only show **New: Ms** when you show a new file.

- Excellent to filter with **NEW**
- If you can add this filter why not, the real file date/time can help if we replace a file by an other one. Why do you want to add it ?

**Comment by gazpan** [comment]
Hi, I've made some small changes, can you try again please?

**Comment by Darknior** [comment]
Excellent now i think it is perfect, this bug is done :)

**Comment by gazpan** [comment]
Great thanks :)
