### ISSUE TITLE
VIDEO s-index with OMX Player

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#10]
https://github.com/gazpan/WebtroPie/commit/1648c4bc19e34cbc1bf846307ba0053401ad87b3

There you have fix VIDEO Z-INDEX.
But if you can, think to fix it for OMX Player users, it will be more accurate.
With VLC a LOGO can be in front of the VIDEO, but with OMXPlayer all is behind the video. Impossible to fix the z-index at this day. ALL is behind OMX, you can force it with a 5000 z-index lol

You have only to read the ES settings from config.php and read if OMX is used or not.

`VideoOmxPlayer: true`

**Comment by gazpan** [comment]
OK, I've done that, it's strange though, in a way we're replicating a limitation and going against the intentions of the theme designer. So, I'm happy to have it this way as it is more like ES, but maybe one day someone might ask for it to behave the other way

**Comment by Darknior** [comment]
Yes it's a limitation with OMXPlayer and for the moment nobody found a solution to fix it, maybe one day ...

**Comment by Darknior** [comment]
Now is done too, you can remove this bug tracker.
But this fix add a new bug, Like the video has z-index 5000 when i open the popup to update game data, the video is under the popup :(
You must put the popup to z-index higher like 5010 to fix it ;)

**Comment by gazpan** [comment]
I've changed the z-index for menu, helper and editor now so that they should be over video. Hope this has fixed the issue now. Thanks

**Comment by Darknior** [comment]
Perfect it works fine you can close this issue.

**Comment by gazpan** [comment]
cheers!
