### ISSUE TITLE
Web access in settings

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#19]
In this file i see your **WanEditMode** option : 

https://github.com/gazpan/WebtroPie/blob/master/app/config/settings.cfg
`WanEditMode : By default (false) all devices on 192.168.* network have write access, when true there is no restriction.`

At start you set it at **false**, now you change to **true**.
I will make some test with this option to see if friends can work on my PI with internet.
And will report you.
Maybe it can be  a good idea to let it false by default, and add it to settings to let user change it easily.

**Comment by gazpan** [comment]
Hi, I'm sorry I didn't see this message until now. It's very cool for me to see it in action on another system!

Strange, I've just now been rearranging menu access, sessions for multi users and better language support. I just need to test.

The way save works is, when you save a game it's just posts only the changed values for the one game. None of the other games are changed and none of the other unchanged fields are changed.
So, if one person updates one game and another changes another game then nothing gets overwritten, or even changing different fields of the same game would be ok too.

In the event that two people try to save at exactly the same time php should wait for a write lock on the gamelist file, one of the processes should wait (although I haven't tried this yet, I guess I could leave an fopen+w open while trying to update a game and check that an error gets reported back cleanly - a large file save may take a little while to write, I'm not sure if a write wait timeout would be longer time than it takes to write a file change.

it makes me think though, that it would be good to detect that a game has changed for other people the are logged in, a very basic way could be just compare modified time, either on a timer or when we save and, if changed, then return the new list, there's probably better ways though, I will have a think.

**Comment by Darknior** [comment]
Yes if you can do this, it will fix the problem for multi users, excellent :)
I'm really interested to try it with you.
> detect that a game has changed
Yes it is important too if we work on the same list, timer is a good idea, but it will make an PI access every 30 sec for exemple ... it is many ... stand for an update is an idea, but if the other user update nothing?
Real time with web socket is the best solution but hardest to code :(
And if you reload all the gamelist, it must not reset what the user is working on. If he has open a game and working on it ? And not reset the user gamelist position on top ...
Or maybe i think it now, on gamelist movement ? If the user move you try to search an update every 30 sec, if it not move because working on a game or leave the page, you update nothing. Maybe it can do the trick ?

Yes i work a lot to make all these covers by hand lol ... and i will finish the last 4 logo this night :)
And i will began videos ...

You can DL them if you want, or i can give you an FTP access, it is fastest than my PI lol.

**Comment by gazpan** [comment]
I've committed some changes now, WAN edit mode is in the menu.

I was worried that different users would have different preferences and didn't think that it was right that they could change other users theme for example, so now, these types of settings are stored in a session, they still save to the file if the user is on the same network as the pi but then it would only affect new or users that had never changed their settings.

I've added some sections  to the language files, I've only partially completed the new french text, but this should all be working a little better now.

**Comment by Darknior** [comment]
> WAN edit mode is in the menu.

What do you want to say ? There is no WAN menu ?

>  so now, these types of settings are stored in a session, they still save to the file if the user is on the same network as the pi

Great idea !!

**Comment by gazpan** [comment]
oops! it's there now

**Comment by Darknior** [comment]
> Language: more Lanuage strings, changes show without refresh

Working fine :)

> Match Media

What do you mean with this menu ?

**Comment by gazpan** [comment]
It's when there is a media file in the media directory with the same name as the ROM name but in the game list there is no link to the image or video. It's like scan for media files, ... so much has changed since I first put it in and I haven't tested it for a long time, I will check that it still works.

**Comment by Darknior** [comment]
- Have you seen before my WAN EDIT question ?
- What is logging the SYSTEM LOG TOTAL ? Webtropie use? And where to read this log ?

**Comment by gazpan** [comment]
> What do you want to say ? There is no WAN menu ?

Sorry, it's in the "Other Settings" menu called "WAN Edit", ... I should maybe call it "Web Edit Access" or something like that ...

The option only appears on the Local network

So, the rules for for menus now are

- **UI menu**, visible by all, all options stored in session but local users also write to local settings
- **Other settings**, same as above except below
  - **Scan at startup**, visible on local network or if Web access is true (1)
  - **WAN edit**, visible only on local network
- **Helpbar Settings**, same as UI menu
- **Uploads**, same as Scan at startup (1)

... do you see WAN Edit ?
... (1) maybe external web users shouldn't be able to change these settings ?

what do you think?

**Comment by Darknior** [comment]
Ok i will correct my french translation, thanks,
I have make the GIT PULL
I always see the two options ... in local and on internet, you can try with my IP if you see them too?
Maybe i see them because internet for me is also local ?

Yes mask WAN EDIT for online users.
And same for SCAN on STARTUP because it will use many CPU on my PI every time.
a user will work on one system it SCAN only this one.
Same for LOAD ALL SYSTEM aAT START, maybe in online user version it is not important, the user will load them if he move in menu and only for systems he use.

**Comment by Darknior** [comment]
Updated : https://github.com/gazpan/WebtroPie/pull/20

**Comment by gazpan** [comment]
Hi, I've changed those options now so that they are local only.

When I look at your system I do not see WAN Edit, so yes, I think that even if you connect to your external address maybe the network is finding a shorter route and translating it to the local address.

**Comment by Darknior** [comment]
Excellent, i have test with an other friend and he don't see the 3 first options like you :)
I think now this Issue is done ...
![25552819_1403053089823144_1832652603_o](https://user-images.githubusercontent.com/3703317/34100522-f9c4ea6a-e3e2-11e7-92e6-451ea8ed6f71.jpg)

**Comment by gazpan** [comment]
Thanks

**Comment by Darknior** [comment]
Oups two questions please : 

- Have you hide the LAUNCH button in Web access ? Like i write before it will be a problem if some users use this button :(
- Is it possible and easy for you to add a VISITOR Online mode?
If i want to show some one all stuff already done, to permit some people to move in Webtropie, but NO editing informations with double-click.
And remove in the bottom menu OPTIONS, MENU, EDIT, LAUNCH.
I think it can be a great feature but i don't want to take your time ... 

But this mode will be not compatible with WEB-EDIT. I really don't know how to add it easily ...
Or ... maybe ... playing with ports ?
On port 80 every one using, VISITOR mode, and on an other port the user choose in settings, like port 8666 all editing options are available. Like that if you don't give it to people they don't know it. Maybe they can scan it :p lol
