### ISSUE TITLE
Images upload not working

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#2]
Like you know **images upload** not working fine, i write it here like a post it :p 

- Think to create directory if it not exist
- Add 3 PATH in the Webtropie config to store the media directory.

`<string name="uploadImageDirectory" value="~/medias/${system_name}/box front"/>`
`<string name="uploadLogoDirectory" value="~/medias/${system_name}/logos"/>`
`<string name="uploadVideoDirectory" value="~/medias/${system_name}/videos"/>`

**Comment by Darknior** [comment]
It also save fine the images path if i write them by hand.
And if i upload them by SSH i can see them.

But if the images are already on the PI, and i write the good path, i can't see them without reload the page. Maybe you can add an event listener on the inputs, and when we live it, it try to load the image and show it.

**Comment by Darknior** [comment]
With time your Webtropie is near perfect now :)
I have work on ATARI 800 and made all my game set with your interface and it help me a lot.
Have you try to fix the image upload function ?
To help us to work now on games media.

**Comment by Darknior** [comment]
And think to verify the GAME LIST refresh informations, because i have change an image path this evening ... to try by hand, and the list don't show it if i don't refresh the list.

**Comment by Darknior** [comment]
Now (for me) the most important bug is this one :p 
Make it possible to upload images and videos.
With this feature i will can make a video of your work to show it :)

**Comment by gazpan** [comment]
Hi, I have made a few changes and this should work now. I've written some information in the README.md file under "Config and Settings"
... Note: the media upload is for image, video and marquee ... not logo 9my mistake).
Do you use "thumbnail", I noticed that it is in the docs for game lists, I think scraper scrapes it too, ... the docs say that it is unused at the moment, I'm wondering whether to add it to the Metadata Editor.

**Comment by Darknior** [comment]
I have try your upload for marquee and it works fine. The image is uploaded to the rom directory / marquees like write in the CFG file.
I have change it with my path : **/home/pi/RetroPie/medias/${system_name}/logos**
It works fine too when i clic SAVE.
But when i refresh the page the path is not saved, and the image is on my pi but the path is wrong and i can't see it.
Can you verify the PATH SAVE ?

**Comment by gazpan** [comment]
ok thanks, almost there, sorry about that... I will check tonight

**Comment by Darknior** [comment]
> ok thanks, almost there, sorry about that... I will check tonight

No problem lol I only try your soft, it take me time but YOU make all the work !
I think if you fix the PATH save it will be good for image upload.
We will miss for : 

- Update an existing image. If we clear the path i see i can Drag'n drop again a new image. But maybe a clear button near the path input or an other graphical button can help an user.
And this button can also remove the old image from the PI.
- Add these PATH settings to the MENU for other users, i think that many will never edit the CFG file in SSH.

**Comment by gazpan** [comment]
I've fixed the save and added clear buttons. Yes, I think at some point I should add a path input for this setting to the main menu.

**Comment by Darknior** [comment]
It works really perfectly ! I have try to add and remove some Marquees, Videos, and Box front.

You will hate me but it give me an other ideas :(
I write them here and if you want to add them we can add new issues ...

** In the same menu where we will write the image path :
- Rename MEDIA (cover, logo, video) with same name as ROM. (auto : jpg, png, mp4)
- Resize image with a defined size.
-- Cover size : ??? x ??? pixel max
-- Marquee size : ??? x ??? pixel max

I have a friend who made http://movie-renamer.fr/
And he had this feature because on some system we know we can't use larger image, and we must resize them. The LOGO/MARQUEE with 400 px larger is the best choice on PI.
I know we can do it before upload, but if the upload do it, it make us save time.

**Comment by gazpan** [comment]
I've change the upload to rename the media to match the ROM name now.

Yes, I can add a max size to the config and you are right I think these options should all be changeable in the front end, so I think we should only consider this closed once all options are in the menu.

Would this be a single dimension (square) or should there be a max width and max height for each ?

**Comment by Darknior** [comment]
Max width and max height. The first comme to max is the max use, and the other size is proportional.
Max 720 x 720 pixel can create cover like : 
- 410 x720
- 720 x 405

**Comment by gazpan** [comment]
That's fine, I just reread your earlier post. Do you think the clear button should delete the old media file ?

**Comment by Darknior** [comment]
Yes because if we have change directory in settings, we will have two media file on hard drive.
I think it is better. But is it is an error and the user don't save his change, he will lost his media file :(
Maybe save the old path in memory, and when the user save the game info, if the media path has change, delete the old file, if it not because he replace the old file or do nothing, you do nothing.
Do you think it's a good solution ?

**Comment by gazpan** [comment]
hi, I've added options to automatically resize image and marquee if the uploaded file is too big.

The automatic deletion of the old media is not done yet.

**Comment by Darknior** [comment]
```
<string name="maxImageSize" value="720x720"/>
<string name="maxMarqueeSize" value="200x400"/>
```
It is better to use it by default.
It is the best for PI.

**Comment by gazpan** [comment]
Thanks, I will change that later and look to add these and other settings onto the main menu as well as the user preferences issue

**Comment by gazpan** [comment]
The defaults have been changed

**Comment by Darknior** [comment]
Thanks it's perfect now :)

**Comment by gazpan** [comment]
Closing now that the settings are in the menu

**Comment by Darknior** [comment]
Sorry finally i found a new bug or limitation ?
When i upload a video it works if the video is little than 1.68 Mo
I have try some with 2.30 2.16 and more Mo and it's not working :(
The finish processing is never done.
Can you fix it please ? Some videos can take 5 Mo if i remember fine ....

**Comment by gazpan** [comment]
This is almost certainly the php upload limit, maybe I should make this adjustable in the system but I've added a .htaccess file containing bigger limits (32M), can you give it a go please?, I'm not sure but I may need to add upload limits to the form tags too

**Comment by Darknior** [comment]
My biggest video preview of 40 sec take me 13Mo and i can't compress it better :(
Maybe because it's raining in game ... many sprite moving ...
I see you put the limit to 32Mo it's a good idea. No limit is better for sure ...

```
http://192.168.1.21/app/svr/game_media_upload.php
{"success":false}
```

For a video of 7.55 Mo

**Comment by Darknior** [comment]
I have try to put the **.htaccess** to **/var/www/html** but it change nothing :(

**Comment by Darknior** [comment]
With a little video file - 2Mo 

`{"success":true,"media_path":"\/home\/pi\/RetroPie\/medias\/ports\/videos\/Cave Story (Japan) [T-En v1.03 by AeonGenesis].mp4","media_url":"medias\/ports\/videos\/Cave Story (Japan) [T-En v1.03 by AeonGenesis].mp4"}
`
But **/home/pi/RetroPie/medias/ports/videos** is always empty :(

Strange because it works fine on my old SD before crash ....
And i always use the same USB HDD for Games and Media ...

**Comment by gazpan** [comment]
ok, maybe it should have been

php5_value upload_max_filesize 32M
php5_value post_max_size 32M
php5_value memory_limit 32M

but it only works if AllowOverride Options is set in the apache config anyway which it probably isn't

I think the easiest thing to do for now is to edit /etc/php5/apache2/php.ini and set 
upload_max_filesize 32M
post_max_size 32M
memory_limit 32M

sudo /etc/init.d/apache2 restart

but I will have to find a nice script way of doing this or perhaps I need to set up a proper apache configuration with overrides set for htaccess to work

do you think most people would want WebtroPie at their web root ?... hmm it's got to be optional i think

**Comment by gazpan** [comment]
I'm wondering again if apache is running as pi user, as in needs permission to write to that directory
ps
`
$ ps -fade | grep apache

root     20957     1  0 11:32 ?        00:00:00 /usr/sbin/apache2 -k start
**pi**       20961 20957  0 11:32 ?        00:00:00 /usr/sbin/apache2 -k start
pi       20962 20957  0 11:32 ?        00:00:00 /usr/sbin/apache2 -k start
pi       20963 20957  0 11:32 ?        00:00:00 /usr/sbin/apache2 -k start
pi       20964 20957  0 11:32 ?        00:00:00 /usr/sbin/apache2 -k start
pi       21023 20957  0 11:32 ?        00:00:00 /usr/sbin/apache2 -k start
pi       21105 20957  0 11:33 ?        00:00:00 /usr/sbin/apache2 -k start
pi       21106 20957  0 11:33 ?        00:00:00 /usr/sbin/apache2 -k start
pi       21107 20957  0 11:33 ?        00:00:00 /usr/sbin/apache2 -k start
pi       21108 20957  0 11:33 ?        00:00:00 /usr/sbin/apache2 -k start
pi       21109 20957  0 11:33 ?        00:00:00 /usr/sbin/apache2 -k start
`

**Comment by Darknior** [comment]
I don't understand why now i must do it, and before i don't ... strange ... or maybe an other app modify it on my old SD.

**Comment by Darknior** [comment]
I have update my PHP.INI with 128M  because i know some media take 30 60 Mo and restart Apache.
Now it works fine.
Like you write you must found a solution to update it with INSTALL.SH

**Comment by Darknior** [comment]
> do you think most people would want WebtroPie at their web root ?... hmm it's got to be optional i think

You're right, it is an option, because we can use many Web console to make different things ...

**Comment by gazpan** [comment]
Hi, I've added this to the INSTALL.sh now at 128M, I've also added a stand alone web server way of running it without apache, it's maybe not as fast but sometimes shows useful error reporting

**Comment by Darknior** [comment]
I read this commit that is excellent and will help many users https://github.com/gazpan/WebtroPie/commit/8402f6c3af79ddbf539b0a571ae9cac5f0428f4e

For me all is working fine with the modif i made myself.
Do you think i must try to UNINSTALL and INSTALL again your Webtropie ?

I will continue to use it with Apache, it's fine for me. But your PHP server is a good idea :)
I will use the Apache INDEX.HTML page to redirect on multiple console i want to use.

**Comment by Darknior** [comment]
Finally it's fine that my SD crash, it permit us to fix many problems for new users :)

**Comment by gazpan** [comment]
hi, you don't need to uninstall and install, the main things were the upload limit and the apache user setting that you have already modified.

Note: installing and choosing stand alone doesn't undo any of the apache settings,it allows the stand alone script to work and both ways of accessing can work at the same time

**Comment by gazpan** [comment]
... oh yes, in a way it turned out to be a good thing that your SD card crashed, perhaps people tried to install and couldn't get it to work and gave up but now, in future it should work for more people.
