### ISSUE TITLE
Options/Scan ERROR

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#22]
I have a curious new bug ...
You can see it in my ARCADE page : http://???.???.??.??/app/#!/arcade

- When i enter there is no problem.
- I launch **SCAN**.
- New games are add, with YELLOW color :)
- You can found some : **mwalkbl2, rampage, skns** and the **mame2003** directory.
Some games (not working) that my friend remove from the gamelist.cfg and forgot to remove files.
SKNS is a BIOS i must HIDE in XML file. And mame2003 the BIOS and settings directory.

But there is a bug in CONSOLE because it write now i have some duplicate files : **duplicates = 6**

```
duplicates
game.service.js:657 undefined
game.service.js:657 undefined
game.service.js:657 undefined
game.service.js:657 undefined
game.service.js:657 undefined
game.service.js:657 undefined
```
But like you can see there are UNDEFINED, i don't really understand.

**Comment by Darknior** [comment]
You can try this on my PI, now i can't SCAN any game directory :(
I try on PORTS, ATARI 800, PSX, before it works now nothing change :(

**Comment by Darknior** [comment]
@gazpan  I have search a little but i really don't understand what you change and break this feature ???

**Comment by gazpan** [comment]
Hi sorry about that, the cache improvement that I reintroduced interfered with scanning. It should be ok now

**Comment by Darknior** [comment]
Ok thanks now it works again :)
