### ISSUE TITLE
Informations not saved

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#3]
The fix you made to save the informations is fine.
But there is one information it not same, the **description**. It stay empty when i reload the page.

https://github.com/gazpan/WebtroPie/commit/275b4121bae8d3ae03c00a38f824c4119aea57c0

**Comment by Darknior** [comment]
For the informations already exist and only update it's ok.
For informations it must add the the XML, it save all the TAGS on a single line.

<rating>0.8</rating><releasedate>20140312T000000</releasedate><developer>Protomank</developer> ...

Maybe you forget /n after each line.

**Comment by gazpan** [comment]
Hi, I've pushed a change which I hope will fix this problem. It should save the description now, however I haven't done anything with white space, I tested on one of my games that has paragraphs separated by spaces and it seems to be working ok. All of the tags are on separate lines as I see it, I am looking at the gamelist.xml with vi directly in raspbian.

**Comment by Darknior** [comment]
Perfect, now it works fine for the **DESC** :)

FAVORITE and KIDGAME always save on same line.

**Comment by gazpan** [comment]
Save game should format the output now so that FAVORITE and KIDGAME are on different lines.
Have a go, this maybe closed now do you think ?

**Comment by gazpan** [comment]
I also noticed that new scan game was not saving but this should be ok now

**Comment by Darknior** [comment]
I really want to try all these improvement but i'm sad, i will be locked all the day, nothing works after the **git pull** !

```
angular.js:14642 TypeError: Cannot read property 'view' of undefined
    at createDefaultSystem (theme.service.js:217)
    at decodeTheme (theme.service.js:419)
    at onSuccess (theme.service.js:583)
    at processQueue (angular.js:17000)
    at angular.js:17044
    at Scope.$digest (angular.js:18182)
    at Scope.$apply (angular.js:18480)
    at done (angular.js:12501)
    at completeRequest (angular.js:12727)
    at XMLHttpRequest.requestLoaded (angular.js:12655) "Possibly unhandled rejection: {}"
```

And it is empty in the CFG file.
HELP please.

**Comment by gazpan** [comment]
Sorry about that, I'm not sure but think it may be to do with error reporting level, I've quickly temporarily put this back in theme.php, can you try again?, ... I will be back later in a few hours

**Comment by gazpan** [comment]
Please try git pull. Sorry for the error, hope the new changes make up for lost time

**Comment by Darknior** [comment]
Yes now it works fine, thanks :)
I only have a CONSOLE error when i change lang : 
```
ReferenceError: LANG is not defined
    at controller.languageChanged (app.controller.js:106)
    at fn (eval at compile (angular.js:15500), <anonymous>:4:174)
    at ChildScope.$eval (angular.js:18372)
    at angular.js:26252
    at Object.<anonymous> (angular.js:29104)
    at forEach (angular.js:410)
    at Object.$$writeModelToScope (angular.js:29102)
    at writeToModelIfNeeded (angular.js:29095)
    at angular.js:29089
    at validationDone (angular.js:29014)
```
But it don't crash Webtropie, and i must REFRESH with F5 to see the lang change.

**Comment by Darknior** [comment]
Now saving in multi line is working fine, i think we can close this issue.

**Comment by gazpan** [comment]
Thanks for fixing the 'modified' I think that might have been the previous error.
