### ISSUE TITLE
Show "Duplicate" on gamelist

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#30]
Showing "Duplicate: " games similar to "New:", "Missing: " games ... will help to remove them.
And permit to remove the CONSOLE information. It's more user friendly.

**Comment by gazpan** [comment]
I've added this, although I liked New as it's gold colour I've switched it around so that New is green, duplicate is gold and missing is red, I thought it was a bit more intuitive that way

**Comment by Darknior** [comment]
I have try it and it is perfect :D 
You have choose the good colors ...
![sans titre-1](https://user-images.githubusercontent.com/3703317/35362635-6b475bf0-0166-11e8-9e0e-0ebae6a1042c.jpg)
You are so fast ... and can close this issue too :p

**Comment by gazpan** [comment]
hey, thanks for the screenshot, I'll use that for the Wiki, I still have a couple of pages to write, ... it' like running, it's slow going but I'm glad I did it when it's done :)

**Comment by Darknior** [comment]
Cool, when it's will be possible when i will try new feature i will send you some other :)
Yes writing wiki is a little boring ... but it's really important and so few coders do it for users ...
You're right to write it every time you add a new feature :)
And your wiki is really fine, maybe it can be a good idea to add a **LINK** name **HELP** in Webtropie, to **open your Wiki** in an other tab with **target="_blank"**.
Maybe in the HOME MENU ?

**Comment by gazpan** [comment]
yes, good idea. a button on the Helpbar "Help", I think I'll quickly add that just a a simple link to the first page, ... it could be context sensitive so that it goes to the right page depending on where you are, but maybe later for that, for now just simple link on the home screen.

thanks again ideas ideas ideas !!

**Comment by gazpan** [comment]
yes, I wished I'd started the wiki at the earlier lol!
... just done https://github.com/gazpan/WebtroPie/wiki/EmulationStation , not sure if it needed it but it's there.
... I'll do a page on the special game flags for New, Missing and Duplicate tomorrow now and start having a look at other issues
ta

**Comment by Darknior** [comment]
> ... just done https://github.com/gazpan/WebtroPie/wiki/EmulationStation , not sure if it needed it but it's there.

Really fine :)

**Comment by gazpan** [comment]
I tried as a link but realised that I needed to pick up the theme colours, so I've done it a little different with a click and window open, it seems to work in chrome but I haven't tested IE yet, sometime browsers block opening new tabs from js, if so I might have to do a bit more work

... I called the button Dépanner ... not sure if that is right

**Comment by Darknior** [comment]
Ok it works fine for me on **Chrome, Firefox and IE** :)
I don't find it in **lang-fr.cfg** ... Dépanner is not really wrong but in french we will use **AIDE** that is more than HELP.
