### ISSUE TITLE
BUG: Recording crash

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#35]
When i take a "NEW" game, and try to add it a **DESCRIPTION** the **Record action never end**.
Like a crash, but if a refresh the web page, the game is recorded. But with an **empty Description**.
I can only add Description to an **already existing** game !
I have this bug only with Description.

**Comment by Darknior** [comment]
I finally have the crash with all the meta-data. But the other data are recording. Not like Description.
Empty saving ... same issue ...
I can't normally record a new game.

**Comment by gazpan** [comment]
This should be ok now too, sorry about that

**Comment by Darknior** [comment]
Ok cool i think you can close the issue, when i try it it works fine.
