### ISSUE TITLE
BUG: On game DELETE

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#36]
- On the game delete popup you forgot to **Uppercase** the first word letter.
- The **checkbox is not working**, you always remove games from hard drive.

**Comment by gazpan** [comment]
Thanks, this should be ok now

I'll modify the wiki later to add install stable (from latest release) instructions instead of from git master

**Comment by gazpan** [comment]
... by the way, great post on retropie, I'd like to pin it to the top of the thread but couldn't see how to do it on the forum, maybe I just have to edit the 1st post and cut and paste it ?

**Comment by Darknior** [comment]
Works fine now too :)

Yes you can, copie my text and modify it like you want :D

**Comment by Darknior** [comment]
You can close this issue :)
I will make some better videos later.
One video by functionality is better i think.

**Comment by gazpan** [comment]
great thanks, will do
