### ISSUE TITLE
WebtroPie dont delete roms

### ISSUE THREAD

**Issue by scalpmonkey** [gazpan/WebtroPie#45]
After hitting DELETE and check "Also delete the ROM file?" the roms are still there. Any quick fix for that? Am I missing something?

**Comment by Darknior** [comment]
Strange last time i try it it works fine for games in gamelist.xml

**Comment by gazpan** [comment]
Hi, I know it's unlikely but does the pi user (or the user that's running WebtroPie) have permissions to delete the file?, ... I think that user would have to have execute permission on the directory to delete files within it (which I've always thought a little bit odd!)

**Comment by Darknior** [comment]
Games are on the MEDIA directory.
MEDIA dir is used by the PI USER, on SDCard and on USB drive.
Webtropie use also the PI USER, i think there is no problem for it to delete or upload a file.

**Comment by scalpmonkey** [comment]
With which user should Webtro be installed? pi or root?

**Comment by Darknior** [comment]
User PI
I write it the message before.

Read the [install.sh](https://github.com/gazpan/WebtroPie/blob/master/INSTALL.sh) line 124 : 

`    # must be run as pi (not root)`

**Comment by scalpmonkey** [comment]
That was it. I forgot that I was logged in with root. Installing with pi user did the job. 
Thanks.

**Comment by Darknior** [comment]
I have made some try today : 
- Remove a game from my game list, a game not in my gamelist.xml and it works fine.
- Remove a game from my gamelist.xml but not the file, it works.
- Remove a game from my gamelist.xml with the file and it works too.
I think you can close this issue.

**Comment by Darknior** [comment]
you can close this issue

**Comment by gazpan** [comment]
thanks very much
