### ISSUE TITLE
BUG: Ratting color error

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#47]
There is an color error on the ratting image : 

![35635142-c6d81c6a-06ad-11e8-931a-66c8ab0032ba](https://user-images.githubusercontent.com/3703317/38201995-7eef1102-369a-11e8-8192-6a9e7d8ad432.jpg)

I use a gray star image and you force a yellow color on it.

![star-gray](https://user-images.githubusercontent.com/3703317/38202026-9e59a64c-369a-11e8-8f44-52d5d645d188.png)
![star-gray-empty](https://user-images.githubusercontent.com/3703317/38202027-9ff04114-369a-11e8-9f6e-840c33ec628b.png)

```
			<rating name="md_rating">
				<pos>0.0255 0.8779</pos>
				<size>0.1406 0.0594</size>
				<!-- <color>bebebeff</color> -->
				<filledPath>./_art/rating/star-gray.png</filledPath>
				<unfilledPath>./_art/rating/star-gray-empty.png</unfilledPath>
			</rating>
```

**Comment by gazpan** [comment]
That's fixed now, thanks

**Comment by Darknior** [comment]
Yes it's perfect, thanks :D
