### ISSUE TITLE
BUG: Environnemental variable not working fine

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#48]
**NORMAL** variable are working fine :)
I use them on my skin.

But i can't use the **ENVIRONMENTAL** variables.
I know they don't work fine in the DEV ES branch, but i can't make them working fine on Webtropie ?

System variable come from **es_systems.cfg**

Ex : `./art/logo/${system.theme}.svg`

```
${system.name} nes
${system.fullName} Nintendo Entertainment System
${system.theme} nes
```

Forum for ES : https://retropie.org.uk/forum/topic/7156/variable-support-in-themes-in-emulationstation/85

**Comment by gazpan** [comment]
Hi, these should be working and I think they're working ok in other themes

I remember it was one of the reasons ones mini and switch themes weren't working until I fixed system variables.

some themes use the full name for a text
<text>${system.fullName}</text>
or use theme dynamically in image paths
<path>./art/${system.theme}.png</path>

if you want to see examples in other themes, cd to themes directory and do :-
find . -name "*.xml" -exec grep -i "\${system\.theme\}" {} \;
or
find . -name "*.xml" -exec grep -il "\${system\.theme\}" {} \;

But there could be some cases where it doesn't work, can you give me an example of where they don't work for you ?

**Comment by Darknior** [comment]
Ok thanks sorry, i have try and it's works fine.
When i've try them some month ago, it was not working and i don't try them again.
Thanks

**Comment by Darknior** [comment]
Arg i speak so fast :(
I use VARIABLE in different place without any problem, and my LIGHT SKIN version too.
But i have try to change one thing on my skin and it not works fine i don't know why : 
Nothing special, i do like in other place 

```
		<image name="bg-image" extra="true">
			<origin>0 0</origin>
			<pos>0.0151 0.0445</pos>
			<size>0.9698 0.911</size>
			<path>./${system.theme}/background.jpg</path>
			<default>./_art/white.png</default>
			<color>ffffff1A</color>
			<tile>true</tile>
			<zIndex>5</zIndex> <!-- Default -->
		</image>
```
It works fine on the real ES but on Webtropie : 

![bug01](https://user-images.githubusercontent.com/3703317/38280369-2e40be02-37a5-11e8-9947-453d684748d6.jpg)

**Comment by Darknior** [comment]
Hooo i think i understand, it's because i'm not in the system, but in front of the system.
And i try to use the environmental variable to catch the background.
It works fine when i'm IN the system, but not OUT.
I have try again with more variable and it works fine on real ES, we can do that.

**Comment by gazpan** [comment]
I was able to reproduce the problem when I added the path ./${system.theme}/background.jpg to the RVGM/theme.xml and remove the path from the RVGM/x6800/theme.xml, it should be ok now, can you try it again please?

**Comment by Darknior** [comment]
Yes it's what i do too.
Perfect it's works fine now :)
You can close too

**Comment by gazpan** [comment]
Thanks!
