### ISSUE TITLE
BUG: Adding logoText support for Caroussel

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#49]
Adding the <logoText> TAG on Caroussel to show text if there is no logo.

https://github.com/RetroPie/EmulationStation/blob/master/THEMES.md

- System Logo/Text - 50
text name="logoText"
- text name="logoText" - ALL
Displays the name of the system. Only present if no "logo" image is specified. Displayed at the top of the screen, centered by default.
- text name="logoText" - FONT_PATH | COLOR | FORCE_UPPERCASE
A logo text, to be displayed system name in the system logo carousel when no logo is available.

```
			<!-- To replace default image LOGO by default -->
			<!-- No declare System LOGO here -->
			<text name="logoText">
				<origin>0 0</origin>
				<pos>0.5 0.5</pos>
				<size>0.2005 0.0959</size>
				<fontSize>0.05</fontSize>
				<fontPath>./_art/Roboto-Medium.ttf</fontPath>
				<alignment>center</alignment>
				<forceUppercase>true</forceUppercase>
				<color>${logoColor}</color>
			</text>
```

**Comment by gazpan** [comment]
This should be ok now, can you give it a try please?

**Comment by gazpan** [comment]
Great!, thank you
