### ISSUE TITLE
Last played date should show as 'Time ago' format

### ISSUE THREAD

**Issue by gazpan** [gazpan/WebtroPie#5]
Within themed page and gamelists, last played should show as time played ago.

**Comment by gazpan** [comment]
Modified and Last Played show in game lists in a time ago format.
At the moment, last played as a theme element still shows in date format.

**Comment by Darknior** [comment]
Yes i can read NEVER or ??/??/????

**Comment by gazpan** [comment]
Hi, I don't understand why it should be in the right place, the last played looks like it should be to the right of the label but if I look at atari800/theme.xml I see that the x position of the md_lastplayed is 27 and the x position of the md_lbl_lastplayed is 32 ?, ... I don't understand ?, shouldn't it be bigger like it is with play count ?

       <text name="md_lbl_playcount">
            <pos>0.420 0.825</pos>
            <size>0.3 0</size>
        </text>

            <text name="md_playcount">
            <pos>0.520 0.795</pos>
            <size>0.02 0.1</size>
        </text>

            <text name="md_lbl_lastplayed">
            <pos>0.320 0.865</pos>
            <size>0.09 0</size>
        </text>

            <text name="md_lastplayed">
            <pos>0.270 0.865</pos>
            <size>0.02 0.1</size>
        </text>

**Comment by Darknior** [comment]
I ha ve this on skin : 

```
		<text name="md_lbl_players, md_players">
			<fontSize>0.025</fontSize>
			<pos>0.320 0.825</pos>
			<size>0.09 0</size>
		</text>
		<text name="md_players">
			<pos>0.385 0.825</pos>
			<size>0.02 0</size>
		</text>
		
		<text name="md_lbl_playcount">
			<pos>0.420 0.825</pos>
			<size>0.3 0</size>
		</text>
		<text name="md_playcount">
			<pos>0.520 0.795</pos>
			<size>0.02 0.1</size>
		</text>
		
		<text name="md_lbl_lastplayed">
			<pos>0.320 0.865</pos>
			<size>0.09 0</size>
		</text>
		<text name="md_lastplayed">
			<pos>0.270 0.865</pos>
			<size>0.02 0.1</size>
		</text>
```

**Comment by gazpan** [comment]
yes, and webtropie puts last played label at x=32% and last played field at x=27% which looks wrong to me

**Comment by Darknior** [comment]
Yes it's wrong ... but it's hard to me to help you with this i never made a skin, i will do mine this month. After i think i will understand better all of this :D 
This one is a beta made by Gilou, a friend, i only debug some mistake ...

**Comment by gazpan** [comment]
I will be good to know how ES corrects this error, there must be some rule that it does to correct these things, maybe if md_lbl.y == md.y and md.x < md_lbl.x then md.x = md_lbl.x + md_lbl.w ... ?
I will have to study the ES code, it will be the only way in the end to make WebtroPie behave as ES does.

**Comment by Darknior** [comment]
And how do you think i must correct my skin, to try ?

**Comment by gazpan** [comment]
maybe 

```
<text name="md_lastplayed">
	<pos>0.4 0.865</pos>
	<size>0.02 0.1</size>
</text>
```

but, I'd rather change WebtroPie to do whatever ES does so that it works for other errors

**Comment by Darknior** [comment]
I have try and it not working too ... so strange ...
Only for Atari 800, you can see it.

The include write : 

```
		<text name="md_lbl_lastplayed">
			<fontPath>./art/Cabin-Bold.ttf</fontPath>
			<pos>0.670 0.34</pos>
			<size>0.1 0</size>
		</text>
		<text name="md_lastplayed">
			<color>969696</color>
			<pos>0.620 0.42</pos>
			<size>0.02 0.1</size>
		</text>
```

I think the XML in a system directory overide the master XML. He always use same font and color, only overide the position.
But only for this VALUE it's not working fine ... strange ...

**Comment by gazpan** [comment]
The last played date should show in time ago format now. E.g. "1 YEAR AGO" or "IL Y A 1 AN"

There is still styling issue because there are two positions for md_lastplayed, one in theme.xml subdirectory and one in the top directory. There are also two color attributes for md_lastplayed, one in the top directory in the combined 'basic, detailed' view, and one just in the 'detailed' view (i think it was).

I think that I can fix the color issue but am still confused by the position since both seem to be the wrong values. I have been looking at the ES code but haven't found the answer yet.

**Comment by gazpan** [comment]
This should be ok now, the confusion was that ES will ignore position tag inside <**text** name="md_lastplayed"> and anchor the field to the label, if the tag was '**datetime**' instead of '**tex**t' then the position attributes will be used and the field won't be anchored, so, I think it's a little quirk that I have had to replicate.

I made some other tweaks to do with styling so it should look a little tidier now.

There is also an option that is on by default to show animations better however this undoes the change to have a fast carousel, so you may want to turn this off.

Merry xmas.

**Comment by Darknior** [comment]
I have take an old image of my system because my last PI SDCard crash :(
And i install again your Webtropie but i have so many strange bugs i don't understand.

Now Lastplayed is working fine and in good place.

But at start :
```
content-script.bundle.js:333 loading pref showConsoleLogs before prefs were initialised, you will not get the correct result
getPref @ content-script.bundle.js:333
(anonymous) @ content-script.bundle.js:481
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:521
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:593
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:621
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1352
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1668
a @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:2103
a @ content-script.bundle.js:1
u @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:2112
(anonymous) @ content-script.bundle.js:1
(anonymous) @ content-script.bundle.js:2106
```
And when i want to change Skin : 
```
angular.js:14642 TypeError: Cannot read property 'image' of undefined
    at theme.service.js:499
    at Object.forEach (angular.js:424)
    at theme.service.js:495
    at Object.forEach (angular.js:424)
    at theme.service.js:493
    at Object.forEach (angular.js:424)
    at findStaticImages (theme.service.js:491)
    at decodeTheme (theme.service.js:480)
    at onSuccess (theme.service.js:642)
    at processQueue (angular.js:17000) "Possibly unhandled rejection: {}"
```
- The directory **/home/pi/.webtropie** is never created :(
I must copy my old one if i want it.
- All options are saving on the Navigator but not the PATH info i can't save :(
I must use the CFG file for them !
- The new Animation option never save.
- I have try to make some UPLOAD and it not working :(
`angular-animate.min.js:11 GET http://192.168.1.21/app/svr/medias/msx2/box%20front/Gradius%203%20-%20The%20Eve%20of%20Destruction%20(Cart)%20(Japan).jpg 404 (Not Found)`
I have try t create manually directories but it dosn't help :(

I really have a problem with setting save. And i do all in local ... it is trange ...
You can see my Webtropie at same URL than before.

Have you see my other bug here ?
https://github.com/gazpan/WebtroPie/issues/2#issuecomment-350575765

Merry xmas friend :)

**Comment by gazpan** [comment]
hi, those are strange errors, especially the first one.
"content-script.bundle.js" is not part of WebtroPie, I haven't done any bundling or minification optimisations perhaps I should

It maybe a message from a browser plugin, there are lots of results if you search for "content-script.bundle.js:333 loading pref showConsoleLogs before prefs were initialised"

/home/pi/.webtropie gets created the first time that you make a change to a setting, it doesn't get created otherwise. Yes, either copy your old preferences or you would have to select them again.

The media problem should be ok now sorry about that

As you say the biggest problem seems to be that your settings changes aren't saving, when you save, in dev tools under network there should be a config_save.php for each time you make a change, ... what is the response of this? you should be able to preview the result

Oh, thanks I didn't see the other bug I will have a look at that

**Comment by Darknior** [comment]
> /home/pi/.webtropie gets created the first time that you make a change to a setting, it doesn't get created otherwise. Yes, either copy your old preferences or you would have to select them again.

I really have a problem with this. Can't you fix it ? If the file not exist create it every time.
Because i import my old one and it read it, but never write in it for now :(
When i want to remove **WAIT FOR ANIMATION** it only save in Browser and if i refresh the option come back :(
Browser save settings is fine for other users, but CFG file is better for the master user.

> As you say the biggest problem seems to be that your settings changes aren't saving, when you save, in dev tools under network there should be a config_save.php for each time you make a change, ... what is the response of this? you should be able to preview the result

`{"changed":true}`

But only save it on Browser.

**Comment by gazpan** [comment]
yes, we will sort it out don't worry

The setting comes from both the .webrtopie directory and session variables - even for local network users, this is incase there are multiple local users that may have different preferences (maybe I should build in proper user/password account admin? especially for WAN edit)

So, I'm guessing at the moment between either the settings file not saving or the settings not saving to the session.

It's easy to check if the file is saving or not by viewing the file and seeing if it changes when you change a menu option. If it isn't saving then it may be a permission problem on the directory or the files themselves, the directory should have read, write and execute permission and the files read, write and be owned by 'pi' user.

... also, check apache is running as pi user, there is some code in the INSTALL.sh script that tries to do this, or maybe it did it but apache hasn't been restarted, try
 ps -fade | grep apache
and see which user is running the process.

checking the session variables would be the next step but for now can you check above and let me know

thanks

**Comment by Darknior** [comment]
```
pi@retropie:~/src/Webtropie $ ps -fade | grep apache
www-data  1846 12156  0 11:39 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  2754 12156  0 12:25 ?        00:00:00 /usr/sbin/apache2 -k start
pi        2863 30554  0 12:31 pts/1    00:00:00 grep --color=auto apache
www-data 11048 12156  0 06:25 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 11050 12156  0 06:25 ?        00:00:01 /usr/sbin/apache2 -k start
www-data 11051 12156  0 06:25 ?        00:00:02 /usr/sbin/apache2 -k start
root     12156     1  0 déc.24 ?      00:00:14 /usr/sbin/apache2 -k start
www-data 17886 12156  0 10:52 ?        00:00:02 /usr/sbin/apache2 -k start
www-data 17887 12156  0 10:52 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 17888 12156  0 10:52 ?        00:00:06 /usr/sbin/apache2 -k start
www-data 18401 12156  0 11:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 31999 12156  0 11:17 ?        00:00:00 /usr/sbin/apache2 -k start
```

**Comment by Darknior** [comment]
> The setting comes from both the .webrtopie directory and session variables - even for local network users, this is incase there are multiple local users that may have different preferences (maybe I should build in proper user/password account admin? especially for WAN edit)

Yes good idea to have multi users on local network.
User/Password account is a good idea but it will take you ma,y time to add...
And yes it will ba fantastic for WAN edit and only let some users work on the PI.

> It's easy to check if the file is saving or not by viewing the file and seeing if it changes when you change a menu option. If it isn't saving then it may be a permission problem on the directory or the files themselves, the directory should have read, write and execute permission and the files read, write and be owned by 'pi' user.

Nothing save, my files last modif came from 18/12/2017 :(
They already use PI user and RWXR-XR-X like you write.

**Comment by gazpan** [comment]
oh, your apache is running as www-data, it needs to be 'pi' so that it can read all the ES config files, roms, media directories and write to /home/pi/.webtropie

there's a few lines of the INSTALL.sh that should change www-data to pi in the apache config, and apache may need to be restarted after.

**Comment by Darknior** [comment]
```
pi@retropie:~/src/Webtropie $ sudo /etc/init.d/apache2 restart
[ ok ] Restarting apache2 (via systemctl): apache2.service.
pi@retropie:~/src/Webtropie $ ps -fade | grep apache
root      3581     1  2 13:02 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  3584  3581  0 13:02 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  3585  3581  0 13:02 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  3586  3581  0 13:02 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  3587  3581  0 13:02 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  3588  3581  0 13:02 ?        00:00:00 /usr/sbin/apache2 -k start
pi        3614 30554  0 13:02 pts/1    00:00:00 grep --color=auto apache
pi@retropie:~/src/Webtropie $
```
Then i reboot to be sure ... and same.

**Comment by Darknior** [comment]
I already use you install.sh i don't understand ...

**Comment by gazpan** [comment]
my apologies it was in the ENABLE_LAUNCH.sh

it's this bit

# change both APACHE_RUN_USER and APACHE_RUN_GROUP
# from www-data to pi
sudo sed 's/\(APACHE_RUN_\(USER\|GROUP\)=\)www-data/\1pi/g' \
    /etc/apache2/envvars.orig > /etc/apache2/envvars
# try to restart apache but may need a reboot if pid not found
sudo apachectl restart

**Comment by Darknior** [comment]
Nothing working fine :(
```
pi@retropie:~/src/Webtropie $ ./ENABLE_LAUNCH.sh
./ENABLE_LAUNCH.sh: ligne 20: /etc/apache2/envvars: Permission non accordée
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

Ready

pi@retropie:~/src/Webtropie $ sudo apachectl restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
pi@retropie:~/src/Webtropie $ sudo /etc/init.d/apache2 restart
[....] Restarting apache2 (via systemctl): apache2.serviceWarning: Unit file of apache2.service changed on disk, 'systemctl daemon-reload' recommended.
. ok
pi@retropie:~/src/Webtropie $ ps -fade | grep apache
root      1371     1  0 13:15 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  1374  1371  0 13:15 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  1375  1371  0 13:15 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  1376  1371  0 13:15 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  1377  1371  0 13:15 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  1378  1371  0 13:15 ?        00:00:00 /usr/sbin/apache2 -k start
pi        1414  1069  0 13:15 pts/0    00:00:00 grep --color=auto apache
pi@retropie:~/src/Webtropie $
```

**Comment by gazpan** [comment]
sudo ./ENABLE_LAUNCH.sh 
should do the trick!

**Comment by Darknior** [comment]
Yes working fine with SUDO, now it use PI, maybe i do it on my old SD ...
And settings.cfg is saving fine now :)

All these bugs only for a USER problem :(
I think you must add this to INSTALL.SH it is really important ...

**Comment by gazpan** [comment]
yes, I agree and I've merged this into the INSTALL.sh now and removed ENABLE_LAUNCH.sh

**Comment by gazpan** [comment]
... I think this issue is resolved too ! :)
