### ISSUE TITLE
BUG: On <releasedate> modification

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#51]
I found a bug today not present before.
When i modify a <releasedate> the SAVE button not appear.
If i modify the date, and modify an other thing to display the SAVE button and save, if i refresh and come back, the other modification works fine, but the date is not modified.

I think Webtropie is not saving the date modification :(

But, it works fine when i creating a new game entry in the gamelist.

**Comment by gazpan** [comment]
This should be ok now

Thanks

**Comment by Darknior** [comment]
Yes perfect :)
You can close this issue ;)
