### ISSUE TITLE
BUG CSS: Limit the LOGO size (WIDTH)

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#52]
Please, just a little CSS trick to add.
Some time the LOGO is really to big, it take all the windows Width, i think it would be nice to limit his size.

![bug](https://user-images.githubusercontent.com/3703317/38307930-b910e942-3815-11e8-9033-4069bdfeb6ee.jpg)

This is perfect : 
```
.game_editor .snap {
    width: 45%;
```
But you force a height on the element, it's a good idea for some of the little logo, but if the ratio WIDTH / HEIGHT is very high, it can create this problem.

```
element.style {
    height: 13vh;
}
```

Maybe you can use javascript to read the `<td class="snap" rowspan="3">` width and limit the LOGO with this width max.
Thanks

**Comment by gazpan** [comment]
I've changed the style with max-width and max-height, I just reread you post - I haven't done it exactly the same as you suggested but I think it should be ok, let me know otherwise.

Thanks

**Comment by Darknior** [comment]
Yes it's fine now, perfect :D 
You can close

**Comment by gazpan** [comment]
Thankyou
