### ISSUE TITLE
Game Editor: Show full size image and image dimensions

### ISSUE THREAD

**Issue by gazpan** [gazpan/WebtroPie#6]
Create a way to preview full size image and show image dimensions, and perhaps file size, date modified.

**Comment by Darknior** [comment]
Maybe  ON 'IMAGE' OVER showing a tips with image in full size, and some informations on bottom : 
- Image size
- File size
- File modified

**Comment by gazpan** [comment]
I've added a mouseover to show a preview and include the size, ... I forgot about the file size + modified, i will change that next time

**Comment by Darknior** [comment]
You have made the most important :) file size + modified is really a bonus.
But i have a bug in your code it not replace fine the IMAGE URL.
![error](https://user-images.githubusercontent.com/3703317/34410420-829a90f2-ebd0-11e7-8aa0-a1d2608894e1.jpg)

**Comment by gazpan** [comment]
thanks, can you try again please?, i think it was because I hadn't " around the url

**Comment by Darknior** [comment]
Yes it is :)
Excellent now it working fine.

**Comment by gazpan** [comment]
I've added modified date and file size now.

**Comment by Darknior** [comment]
Working fine too, excellent :)
You can close this issue.

Now we only miss for : 
- Multiple Select and Action
- Pause, delay or control video preview enhancement

The second is easy to implement i think. Maybe it's time for you to make a new official release :)
For the moment you never made a RELEASE on GITHUB but now users can really use your work, it can be a good idea :)

**Comment by gazpan** [comment]
Hi, yes I've been thinking or what you said a while ago about releasing a 0.9 and then a version 1.0 and perhaps putting back big features to 1.2, 1.3 etc, and I agree.

It would have been nice to have had more useful features done by now but as you say really 1.0 could be the 'core' functionality and WebtroPie has it's uses as it is now.

I have started to prepare for a release, I've added a [Wiki section to the GitHub page](https://github.com/gazpan/WebtroPie/wiki), I will complete the two issues above too.
Maybe to add to the list
* Warning if Emulation Station is already running, with button to close

I think I will trim and update the readme and move more to the wiki.

The three things that I would like to have a go at soon are
* Gridview
* Custom Collections Carousel and list changes (should be done with multi -select add game to custom collection issue above I think)
* System Stats page or pages, disk space and load graphs - I was thinking of having this to come from the RetroPie carousel menu and then showing a list of system type pages.

**Comment by Darknior** [comment]
Your WIKI is really excellent, i like it ... it will help users :)

I don't understand this ?
>Warning if Emulation Station is already running, with button to close

Why do you want to detect if ES is running for ?

1. Custom collection is a great feature, if we can made them from PC with mouse it will really help :)
2. System Stats pages is great too, it is really a cool feature we miss for the moment. But it will take you more work to release, ... disk space, CPU usage, Memory hit, CPU temps, all you can show can help :)
3. Gridview is a cool feature but not release for the moment, you can do it later ...

**Comment by gazpan** [comment]
Because EmulationStation keeps gamelists in memory and overwrites gamelists on exit (unless you change the option) there would be a danger of losing changes.

So, I think that when WebtroPie starts it should show a warning that emulation station is still running, ... offer a button to close it, ... maybe there is an option "Don't show this message again" but I think it should at least tell any new user the warning once, .. what do you think ?, it's the same for any metadata editor, scraper and anything else that might change a gamelist.

Agree, just 1. then for the release :)

Thanks again for all of your help, it's much appreciated.

**Comment by Darknior** [comment]
Yes it is a really good idea, it will help a lot users, i always must explain it too lol
For my part i remove save gamelist on ES exit, i don't lost my work with Webtropie. But i must restart ES to see it on PI ... maybe an button **RESTART ES** on the bottom menu can be a good idea too :)

For the videos, maybe finally you can add a preview after drag n drop. **FFMPEG** can take it from the video, or with **AVCONV**.

`avconv -i $file -ss $seekTime -frames:v 1 $pngFile`
`ffmpeg -i $file -ss $seekTime -frames:v 1 $pngFile`

I have a friend who make this code : 

```
duration=`ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 $f`
    seek=` echo "$duration/2" | bc`
    fname=`basename $f .mp4`
    avconv -i $f -ss $seek -frames:v 1 "/media/duffy/38fc2057-b8cd-4ae9-ac35-452cfd0a21531/Rom/gamecube/assets/extracted/$fname.png"
```
He take the screenshot near the end of the video to try to have the title screen, all the **Emumovies** videos have title at end.

And if you add a **PATH** for **Screenshot** in options, it can AUTO create them for us.
When we have a big hard drive we use video preview, if we play on PI with a SD or little USB Key we use screenshot in **gamelist.xml** :)
- And maybe an option to SWITCH it for all the gamelist can be a good idea too.
- With the option to create all the missing screenshots.

**Comment by Darknior** [comment]
Using ffmpeg with PHP ... some other do it ...
https://sourceforge.net/projects/ffmpeg-pi.raspbian-9-webserver.p/

They speak about ffmpeg here : https://www.raspberrypi.org/forums/viewtopic.php?t=125367

Do you think it is a good idea ?
Encode video on PI3 will take toi many time ... but take a screenshot on a video i think it is possible.

**Comment by gazpan** [comment]
Hi, I'm not sure I understand, is this to show something (preview/screenshot of video) for the video in the editor?, if so I could just play the full video there too, or would that be wrong?

In terms of memory and efficiency it would have already started transferring and playing (if in the theme 'video' view) so it usually will already be transferred and cached in memory.

Or, do you need separate 'screenshot' management anyway for other reasons? ... like if you want to manage box art, poster, screenshot etc ... I'm happy to add additional features but as you know the ES themes only support one image and one marquee, so I could add additions to the editor but it won't be themeable unless the community change the ES theme spec ... thinking about it wasn't there a mention of a  'thumbnail' tag in the ES docs, currently unused?

So, happy to extract an image and add a field in the editor and a feature to scrape screenshots from videos but if you are ok with just seeing the video in the editor that would be much quicker to do

**Comment by gazpan** [comment]
I think I understand you now, I've added the video thumbnail but it would be good to see a full size video image to know it's quality and size, it wouldn't be easy to find the video size from the file but a screenshot using the method that you've described would give that information, I could either show that image or just use that information to size a full size video preview

**Comment by Darknior** [comment]
> In terms of memory and efficiency it would have already started transferring and playing (if in the theme 'video' view) so it usually will already be transferred and cached in memory.

Yes you're right, show little video is perfect.

> Or, do you need separate 'screenshot' management anyway for other reasons? ... like if you want to manage box art, poster, screenshot etc ... I'm happy to add additional features but as you know the ES themes only support one image and one marquee, so I could add additions to the editor but it won't be themeable unless the community change the ES theme spec ... thinking about it wasn't there a mention of a 'thumbnail' tag in the ES docs, currently unused?
So, happy to extract an image and add a field in the editor and a feature to scrape screenshots from videos but if you are ok with just seeing the video in the editor that would be much quicker to do

Yes i think you are right.
But extracting screenshot from video is really a great improvement i never think before .
Some guy's using screenshot some other videos like me, because i have many disk space on my HDD.
If i want to use my PI only with a little SD i will must use Screenshot too to save place.
If Webtropie can generate screenshot from videos and let us switch it auto on gamelist.xml, it will save us time to manage collection on different devices.

- When we upload a video generate the screenshot in his directory we must add to path
- If the system is already done, add a new button in the bottom menu to generate all the missing screenshots.
- Add in the bottom menu or anywhere an option to switch in video or Screenshot.

But i don't understand if on ES we can show screenshot+ cover + logo like we do with video ?
Or if screenshot use the logo or cover place ...
It is important to make the switch.
