### ISSUE TITLE
Allow drag and drop over existing image

### ISSUE THREAD

**Issue by gazpan** [gazpan/WebtroPie#7]
Allow drag and drop over existing image, marquee and video

... and add thumbnail ?

**Comment by gazpan** [comment]
This is done now

**Comment by Darknior** [comment]
WOAW excellent, good news :)
- But it is an invisible option, if you can it will be better with an OUTLINE when the MOUSE OVER the image.
I write OUTLINE because it take no place in CSS, using BORDER will take place move the image.
- And when we save the modif, you don't fix the bug where data are not refresh in gamelist.
We always see them like before, we must move and come back to game to see improvement.

**Comment by gazpan** [comment]
I've changed it so that dragging an image over changes the table cell to have a dashed border and the message 'Drop to upload' (another language thing that I must fix!).

... the second thing though, when I upload an image it is showing in the gamelist immediately, if you don't save the change then it will not be there when you refresh, but if you do save the change then it will be there. ?

**Comment by Darknior** [comment]
I have try the update and : 
- I like the new drag n drop design it's cool :)
- When i drag an image i finally understand that you replace the old image directly. If i save or not it change nothing.
It's cool you can let it. We don't have to save for images.

Bugs : 
- When i have upload an image, i click CANCEL or SAVE, and i go back to GameList.
Then the new image is not visible, i must change game in list and go back on it to see the new image.
I think the easier way is to reload the game information when we click these buttons. All informations SAVE! Only images for CANCEL.

**Comment by gazpan** [comment]
The game list image should update now. :)

**Comment by Darknior** [comment]
Ok i have try it works fine :)
But you will hate me again i found an other bug :(
In your resize function i think ...
- First if the image as the good size, not resize it.
- Second, resize some time give a crappy result i don't know why
I upload this : ![caverns of mars usa](https://user-images.githubusercontent.com/3703317/34018834-1f718cd2-e12c-11e7-8dd3-c52c2434d866.png)
And it save this : 
![caverns of mars usa](https://user-images.githubusercontent.com/3703317/34018851-33ad538e-e12c-11e7-8077-a2cd941db1ed.png)
Maybe you can DL my image to try resize it ?
[Caverns of Mars (USA).zip](https://github.com/gazpan/WebtroPie/files/1561058/Caverns.of.Mars.USA.zip)

**Comment by gazpan** [comment]
I had angular watching the filename, it was ok for me when testing uploading from no image to a new image, or from an image with a different name but not when both images are the same as the rom name, so I changed it to watch the url which includes the modified time of the files and it works all of the time now.
