### ISSUE TITLE
Pause, delay or control video preview

### ISSUE THREAD

**Issue by gazpan** [gazpan/WebtroPie#8]
Pause video control, or mute button

**Comment by Darknior** [comment]
With HTML5 you can easily add a button or let us click the video to PAUSE/PLAY with : 

```
    function vidplay() {
       var video = document.getElementById("Video1");
       var button = document.getElementById("play");
       if (video.paused) {
          video.play();
          button.textContent = "||";
       } else {
          video.pause();
          button.textContent = ">";
       }
    }
```
You can also AUTO PAUSE the video when opening the Popup.

**Comment by Darknior** [comment]
Maybe adding a video logo where we drag n drop the video, because there is one mini cover and Logo but video is empty ... it is not important but it is strange. And it will be complicate to take a screenshot in video, a logo **video uploaded** is a good trick.

**Comment by gazpan** [comment]
I've done a little to this

-  if you click a Video it will Pause or Play
- At the moment I haven't added a mouse over > or || symbol.
- There is an option in the menu to autoplay which is on by default, if switched off videos won't play until either the video is clicked or the setting is changed. Changing the setting also plays or pauses the video (some themes have the video behind an image which makes the video unclickable so this is another way to play or pause the video)
- I've added the theme defined 'delay' functionality
- There is a menu option to mute videos
- There is a menu option to show video controls. Until i saw what they looked like I thought that this would be a bad option as it wouldn't likely match the style of the app but I tried a couple of browsers and it didn't look too bad and thought that it could mostly resolve this issue, but then I added the other controls and now I'm not sure if it's useful

After I added the mute I wondered if we still need the play/pause functionality, if pause is just another way to mute then maybe it's not needed.

So, it's mostly there and should be easy to finish off but thought I'd ask what you thought ...

**Comment by gazpan** [comment]
I've changed the Editor to show the video now, there's not much room so it's a little small, it should start playing when a video is uploaded.
There's a little glitch in that the video behind the editor doesn't start to play immediately, .. I'll fix that

**Comment by gazpan** [comment]
... by the way, I'm using (for real) the app to upload you Atari800 media!, seems strange :)

**Comment by Darknior** [comment]
I love all you add, all is perfect and with all these options every one will find what he want :)
Show video control is cool, i love it on PC it help.
Mini video preview is cool too if you don't generate screenshot.
You must only add an MOUSE OVER ICO to  pause video, and the video info in editor like for images.
And that's all it will be perfect and you close this issue :)

**Comment by Darknior** [comment]
> ... by the way, I'm using (for real) the app to upload you Atari800 media!, seems strange :)

What is strange ? lol to DL my stuff with your Webtropie ?

**Comment by gazpan** [comment]
Hi, your stuff is great lol, I mean it strange using the app instead of coding it.

I've finally added the play/pause now but I decided to refactor how I originally did the previews. There's a zoom in out now and it's click to show preview now instead of mouse over

**Comment by Darknior** [comment]
Yes it's funny lol
I have add 3 new games, for the moment only informations and videos, i will finish covers and logo sooner.

I really love this new preview we must clic with zoom, it's so perfect :)
Informations are write with a less big font, it is better too.
I think you can close this issue now :)

**Comment by gazpan** [comment]
thanks... I think I just found a problem, with sound on moving from a game with video to one without you still hear the sound for the last game video, it should be a simple fix though ... so nearly there

**Comment by Darknior** [comment]
New bug, video control not working now for me. When i want to use it it PLAY or POSE video, your new layer block me the video control menu ...

**Comment by gazpan** [comment]
Hi, I've made a few small changes which may have fixed this can you try again please?

however, I know that there is a problem when the video is behind another image - as on spaceoddity where there are moons and planets, or on some themes that create a raster effect on the video by placing a semi transparent stripe pattern over the video ... for this, it's hard to detect 'mouse over', I could do it by position but on space oddity the video goes behind game list and it's likely that if I just gave it a big z-index that it would show up through other things that it isn't supposed to.

so, I think, it's best to just have it working as mouse over on themes where the video is on top, but if this was the case with your situation then this might be the reason, otherwise hopefully my change has solved it.

**Comment by Darknior** [comment]
No it don't work ... the update break my video config, i uncheck options and check them again and now it's fine, now i can only see the player menu when i PAUSE the video. But i can't use it.
Try on my Webtropie

**Comment by Darknior** [comment]
Strange but now when i come to a gamelist, the first video play sound, Webtropie when only mute the other video i will watch. But never the first one.

**Comment by gazpan** [comment]
Hi, it seems to be ok in Chrome for me but not in safari, I will have a look

**Comment by gazpan** [comment]
It gets to the code to play the video but gives an error in Safari

Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

This seems to be changes made to safari to prevent videos from playing automatically

https://www.macworld.com/article/3206724/websites/how-to-stop-autoplay-videos-in-safari-11.html

**Comment by Darknior** [comment]
Sorry i don't want to boring you ... but i don't see what you fix ?

- I can't use the **VIDEO PLAYER MENU BAR** from you add the **PLAY / PAUSE** layer. You use  **z-index: 5000;**  and the menu is behind.
- I'm on a **gamelist** an check **VIDEO MUTE** and it works! But is i move left on an other gamelist, the video will s**tart with sound** :( The sound will be mute again only if i move on an other video. And if change again to an other gamelist it's same ... the first video always have sound.

I'm using **CHROME**.

**Comment by gazpan** [comment]
Hi, sorry for the late reply.

The theme sets the z-index, video controls layer is always the same z-index as the video but, because it is after the video it always shows on top of the video.

Which theme is it that you can't use the play / pause button ?, I have connected to your WebtroPie and I can play and pause the video with the Dark Steel theme sing Chrome.

I have fixed the Mute problem now.

**Comment by Darknior** [comment]
Yes I understand but it is not my problem. I can play mute too. But I can't use the video menu to change sound or move fast in video. Your play pause layer break this feature. We can show the video player but we can't use it. Do you understand me?

**Comment by gazpan** [comment]
Yes, sorry I understand now, my apologies I will sort something out, thanks for your patience

**Comment by Darknior** [comment]
Ok cool. Sorry for my bad English
No problem for me,  it's my fault...
I'm not at home for 3 days. I will try all your fix Wednesday 😉

**Comment by gazpan** [comment]
No I should have understood, when I read video controls i was thinking the controls that I added instead of the built in controls.

It should be ok now.

sorry again

**Comment by Darknior** [comment]
Hi
Ok now it's ok, i can use the video player.
But the PAUSE / PLAY word is write on left top of the video and not center like before when i over it. Is it normal ?
Thanks

**Comment by Darknior** [comment]
It is not important now it works fine, but will you fix this little bug or not ?
![sans titre-1](https://user-images.githubusercontent.com/3703317/34986780-28c709fa-fab9-11e7-8049-1f71dc12e454.jpg)

**Comment by gazpan** [comment]
Hi, sorry, I've fixed it locally but haven't pushed the change yet, this is because I have done a few other changes that I'm still testing, I've definitely at least one bug still to fix - not sure if it's new or not and will hopefully push the changes later. If I'm not happy with everything I'll see if I can easily just push this fix on it's own.

**Comment by gazpan** [comment]
Hi, I've committed a fix for this now, please can you try again, the error was due to me not using origin in some themes, it initially worked on the ones I tested but they were all centered differently.

**Comment by Darknior** [comment]
Perfect now it works fine, you close this issue :)

**Comment by gazpan** [comment]
thanks
